
service: bot-{PlantID}
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  handle_message:
    handler: handler.handle_message
    events:
      - httpApi:
          path: /bot-{PlantID}
          method: post
